import * as del from 'del';
import * as vinylPaths from 'vinyl-paths';
import * as path from 'path';

export function generate(gulp, config, gulptraum): void {

  const outputFolderPath = path.resolve(config.paths.root, config.paths.output);

  gulptraum.task('build-sass-clean', {
    help: 'Cleans all css files built by the SASS plugin'
  }, () => {
    // TODO: make use of excludes provided in the config
    return gulp.src(`${outputFolderPath}/**/*.css`)
      .pipe(vinylPaths(del));
  });

  gulptraum.task('clean-sass', {
    help: 'Cleans all files generated by the SASS plugin'
  }, (callback) => {

    const tasks = [
      'build-sass-clean',
    ];

    return gulptraum.gulpAdapter.runTasksSequential(tasks, callback);
    
  });
}

module.exports.generate = generate;
